[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 20.0
#normal = { family = "Iosevka NF", style = "Regular" }
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[font.offset]
y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "None"

[window.padding]
x = 5
y = 5

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]
