[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.offset]
y = 20

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "None"

[window.padding]
x = 5
y = 5

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]
